const cli = require('./../lib')

cli.usage('Usage: $0 <command> [options]')
  .option(['-f', '--file'], 'Load a file', 'red')
  .option(['-h', '--help'], 'Show help', 'blue')
  .example('$0 -f foo.js', 'count the lines in the given file')
  .epilog('copyright 2019', 'green')
  .show()

cli.usage('Usage: $0 [options]')
  .option(['-p', '--port'], 'Port to use [3000]')
  .option(['-H', '--host'], 'Address to use [0.0.0.0]')
  .option(['-s', '--silent'], 'Suppress log messages from output')
  .option(['--cors[=headers]'], 'Enable CORS via the "Access-Control-Allow-Origin" header.')
  .option([], 'Optionally provide CORS headers list separated by commas.')
  .option(['-S', '--ssl'], 'Enable https.')
  .option(['-C', ' --cert'], 'Path to ssl cert file (default: cert.pem).')
  .option(['-K', '--key'], 'Path to ssl key file (default: key.pem).')
  .option(['-h', '--help'], 'Print this list and exit.')
  .epilog(`Server package copyright ${new Date().getFullYear()}`)
  .show()
